// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
<<<<<<< HEAD
      return web;
=======
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
>>>>>>> main
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
<<<<<<< HEAD
        return ios;
      case TargetPlatform.macOS:
        return macos;
=======
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
>>>>>>> main
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

<<<<<<< HEAD
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9XZKVI_EzUQydr0-hHsNyfD7Fe873QwM',
    appId: '1:149553189060:web:19f6f9ddc41c7206427991',
    messagingSenderId: '149553189060',
    projectId: 'simple-chat-flutter-ae41a',
    authDomain: 'simple-chat-flutter-ae41a.firebaseapp.com',
    databaseURL: 'https://simple-chat-flutter-ae41a-default-rtdb.firebaseio.com',
    storageBucket: 'simple-chat-flutter-ae41a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2nmq_QTIgMFqj0vOXOusQ0bxb2yq0MbE',
    appId: '1:149553189060:android:8bc910688a3d3460427991',
    messagingSenderId: '149553189060',
    projectId: 'simple-chat-flutter-ae41a',
    databaseURL: 'https://simple-chat-flutter-ae41a-default-rtdb.firebaseio.com',
    storageBucket: 'simple-chat-flutter-ae41a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDgdK1ub0PR9bliyGkyeWBJPowIEY82Ws',
    appId: '1:149553189060:ios:39d118ca3fa367dc427991',
    messagingSenderId: '149553189060',
    projectId: 'simple-chat-flutter-ae41a',
    databaseURL: 'https://simple-chat-flutter-ae41a-default-rtdb.firebaseio.com',
    storageBucket: 'simple-chat-flutter-ae41a.appspot.com',
    iosBundleId: 'com.example.appSmartHouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDgdK1ub0PR9bliyGkyeWBJPowIEY82Ws',
    appId: '1:149553189060:ios:bdcf4303d79df8b2427991',
    messagingSenderId: '149553189060',
    projectId: 'simple-chat-flutter-ae41a',
    databaseURL: 'https://simple-chat-flutter-ae41a-default-rtdb.firebaseio.com',
    storageBucket: 'simple-chat-flutter-ae41a.appspot.com',
    iosBundleId: 'com.example.appSmartHouse.RunnerTests',
=======
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiXu_xLBlXSwj2NIPWNu0GFcJ-EJ2Nh_U',
    appId: '1:154057730301:android:d3f36cd650417aa2917694',
    messagingSenderId: '154057730301',
    projectId: 'appsmarthouse-6b1c5',
    storageBucket: 'appsmarthouse-6b1c5.appspot.com',
>>>>>>> main
  );
}
